[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/7cheese-pizza.apk"
  to = "/7cheese-pizza.apk"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/7cheese-pizza.apk"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment; filename=\"7cheese-pizza.apk\""

[[headers]]
  for = "/.well-known/assetlinks.json"
  [headers.values]
    Content-Type = "application/json"
